algoritmo "Soma"
variáveis
    valor1, valor2, soma, divisao, subtracao, multiplicacao: real
início
    Escreva "Digite o primeiro valor"
    Leia valor1
    Escreva "Digite o segundo valor"
    Leia valor2
    soma = valor1 + valor2
    Escreva "A soma é ", soma
    subtracao = valor1 - valor2
    Escreva "A soma é ", subtracao
    divisao = valor1 / valor2
    Escreva "A soma é ", divisao
    multiplicacao = valor1 * valor2
    Escreva "A soma é ", multiplicacao
Fim
